"""SOFA conventions stored as Python dictionaries."""
from typing import Any

SIMPLEFREEFIELDHRTF_1_0 = {
    "GLOBAL:Conventions": {
        "default": "SOFA",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Version": {
        "default": "2.1",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:SOFAConventions": {
        "default": "SimpleFreeFieldHRTF",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "This conventions is for HRTFs created under conditions where room information is irrelevant",
    },
    "GLOBAL:SOFAConventionsVersion": {
        "default": "1.0",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIName": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIVersion": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationName": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationVersion": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:AuthorContact": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Comment": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DataType": {
        "default": "TF",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:History": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:License": {
        "default": "No license provided, ask the author for permission",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ListenerShortName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "ID of the subject from the database",
    },
    "GLOBAL:Organization": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:References": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:RoomType": {
        "default": "free field",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Origin": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateCreated": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateModified": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Title": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DatabaseName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "name of the database to which these data belong",
    },
    "ListenerPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition": {
        "default": [[0, 0.09, 0], [0, -0.09, 0]],
        "flags": "m",
        "dimensions": "rCI, rCM",
        "type": "double",
        "comment": "",
    },
    "ReceiverPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "Source position is assumed to vary for different directions/positions around the listener",
    },
    "SourcePosition:Type": {
        "default": "spherical",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition:Units": {
        "default": "degree, degree, metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "eCI, eCM",
        "type": "double",
        "comment": "",
    },
    "EmitterPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerUp": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView": {
        "default": [1, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerView:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "N": {
        "default": 0,
        "flags": "m",
        "dimensions": "N",
        "type": "double",
        "comment": "",
    },
    "N:LongName": {
        "default": "frequency",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "narrative name of N",
    },
    "N:Units": {
        "default": "hertz",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Data.Real": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "mRn",
        "type": "double",
        "comment": "",
    },
    "Data.Imag": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "MRN",
        "type": "double",
        "comment": "",
    },
}

SIMPLEFREEFIELDHRTF_1_1 = {
    "GLOBAL:Conventions": {
        "default": "SOFA",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Version": {
        "default": "2.1",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:SOFAConventions": {
        "default": "SimpleFreeFieldHRTF",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "This conventions is for HRTFs created under conditions where room information is irrelevant.",
    },
    "GLOBAL:SOFAConventionsVersion": {
        "default": "1.1",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIName": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIVersion": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationName": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationVersion": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:AuthorContact": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Comment": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DataType": {
        "default": "TF",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:History": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:License": {
        "default": "No license provided, ask the author for permission",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DatabaseName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "Unique name of the database to which these data belong.",
    },
    "GLOBAL:ListenerShortName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "ID of the subject from the database.",
    },
    "GLOBAL:Organization": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:References": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:RoomType": {
        "default": "free field",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Origin": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateCreated": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateModified": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Title": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition": {
        "default": [[0, 0.09, 0], [0, -0.09, 0]],
        "flags": "m",
        "dimensions": "RCI",
        "type": "double",
        "comment": "",
    },
    "ReceiverPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "The source position is assumed to vary around the listener.",
    },
    "SourcePosition:Type": {
        "default": "spherical",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition:Units": {
        "default": "degree, degree, metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "eCI, eCM",
        "type": "double",
        "comment": "Source consists of a single Emitter only.",
    },
    "EmitterPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerUp": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView": {
        "default": [1, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerView:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Data.Real": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "mrn",
        "type": "double",
        "comment": "",
    },
    "Data.Imag": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "MRN",
        "type": "double",
        "comment": "",
    },
    "N": {
        "default": 0,
        "flags": "m",
        "dimensions": "N",
        "type": "double",
        "comment": "",
    },
    "N:LongName": {
        "default": "frequency",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "narrative name of N",
    },
    "N:Units": {
        "default": "hertz",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
}

SIMPLEFREEFIELDHRTF_1_2 = {
    "GLOBAL:Conventions": {
        "default": "SOFA",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Version": {
        "default": "2.1",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:SOFAConventions": {
        "default": "SimpleFreeFieldHRTF",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "This conventions is for HRTFs created under conditions where room information is irrelevant.",
    },
    "GLOBAL:SOFAConventionsVersion": {
        "default": "1.2",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIName": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIVersion": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationName": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationVersion": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:AuthorContact": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Comment": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DataType": {
        "default": "TF",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:History": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:License": {
        "default": "No license provided, ask the author for permission",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DatabaseName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "Unique name of the database to which these data belong.",
    },
    "GLOBAL:ListenerShortName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "ID of the subject from the database.",
    },
    "GLOBAL:Organization": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:References": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:RoomType": {
        "default": "free field",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Origin": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateCreated": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateModified": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Title": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition": {
        "default": [[0, 0.09, 0], [0, -0.09, 0]],
        "flags": "m",
        "dimensions": "RCI",
        "type": "double",
        "comment": "",
    },
    "ReceiverPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "The source position is assumed to vary around the listener.",
    },
    "SourcePosition:Type": {
        "default": "spherical",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition:Units": {
        "default": "degree, degree, metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "eCI, eCM",
        "type": "double",
        "comment": "Source consists of a single Emitter only.",
    },
    "EmitterPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerUp": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView": {
        "default": [1, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerView:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Data.Real": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "mrn",
        "type": "double",
        "comment": "",
    },
    "Data.Imag": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "MRN",
        "type": "double",
        "comment": "",
    },
    "N": {
        "default": 0,
        "flags": "m",
        "dimensions": "N",
        "type": "double",
        "comment": "",
    },
    "N:LongName": {
        "default": "frequency",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "narrative name of N",
    },
    "N:Units": {
        "default": "hertz",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Normalization": {
        "default": 0,
        "flags": "I",
        "dimensions": None,
        "type": "double",
        "comment": "Describing normalization status.",
    },
    "Normalization:Description": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "Narrative explanation of the normalization.",
    },
    "Normalization:References": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "References to publications describing the normalization.",
    },
    "Normalization:URI": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "URIs or DOIs to publications describing the normalization.",
    },
}

SIMPLEFREEFIELDHRIR_1_0 = {
    "GLOBAL:Conventions": {
        "default": "SOFA",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Version": {
        "default": "2.1",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:SOFAConventions": {
        "default": "SimpleFreeFieldHRIR",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "This convention set is for HRIRs recorded under free-field conditions or other IRs created under conditions where room information is irrelevant",
    },
    "GLOBAL:SOFAConventionsVersion": {
        "default": "1.0",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIName": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIVersion": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationName": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationVersion": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:AuthorContact": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Comment": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DataType": {
        "default": "FIR",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:History": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:License": {
        "default": "No license provided, ask the author for permission",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Organization": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:References": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:RoomType": {
        "default": "free field",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Origin": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateCreated": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateModified": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Title": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DatabaseName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "name of the database to which these data belong",
    },
    "GLOBAL:ListenerShortName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "ID of the subject from the database",
    },
    "ListenerPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition": {
        "default": [[0, 0.09, 0], [0, -0.09, 0]],
        "flags": "m",
        "dimensions": "rCI, rCM",
        "type": "double",
        "comment": "",
    },
    "ReceiverPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "Source position is assumed to vary for different directions/positions around the listener",
    },
    "SourcePosition:Type": {
        "default": "spherical",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition:Units": {
        "default": "degree, degree, metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "eCI, eCM",
        "type": "double",
        "comment": "",
    },
    "EmitterPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerUp": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView": {
        "default": [1, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerView:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Data.IR": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "mRn",
        "type": "double",
        "comment": "",
    },
    "Data.SamplingRate": {
        "default": 48000,
        "flags": "m",
        "dimensions": "I, M",
        "type": "double",
        "comment": "",
    },
    "Data.SamplingRate:Units": {
        "default": "hertz",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Data.Delay": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "IR, MR",
        "type": "double",
        "comment": "",
    },
    "SourceUp": {
        "default": [0, 0, 1],
        "flags": None,
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "SourceView": {
        "default": [1, 0, 0],
        "flags": None,
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "SourceView:Type": {
        "default": "cartesian",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourceView:Units": {
        "default": "metre",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
}

SIMPLEFREEFIELDHRIR_1_1 = {
    "GLOBAL:Conventions": {
        "default": "SOFA",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Version": {
        "default": "2.1",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:SOFAConventions": {
        "default": "SimpleFreeFieldHRIR",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "This convention set is for impulse responses recorded under free-field conditions or conditions with irrelevant room information.",
    },
    "GLOBAL:SOFAConventionsVersion": {
        "default": "1.1",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIName": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIVersion": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationName": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationVersion": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:AuthorContact": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Comment": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DataType": {
        "default": "FIR",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:History": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:License": {
        "default": "No license provided, ask the author for permission",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DatabaseName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "Unique name of the database to which these data belong.",
    },
    "GLOBAL:ListenerShortName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "ID of the subject from the database.",
    },
    "GLOBAL:Organization": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:References": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:RoomType": {
        "default": "free field",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Origin": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateCreated": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateModified": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Title": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition": {
        "default": [[0, 0.09, 0], [0, -0.09, 0]],
        "flags": "m",
        "dimensions": "RCI",
        "type": "double",
        "comment": "",
    },
    "ReceiverPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "The source position is assumed to vary around the listener.",
    },
    "SourcePosition:Type": {
        "default": "spherical",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition:Units": {
        "default": "degree, degree, metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "eCI, eCM",
        "type": "double",
        "comment": "Source consists of a single Emitter only.",
    },
    "EmitterPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerUp": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView": {
        "default": [1, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerView:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Data.IR": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "mrn",
        "type": "double",
        "comment": "",
    },
    "Data.SamplingRate": {
        "default": 48000,
        "flags": "m",
        "dimensions": "I, M",
        "type": "double",
        "comment": "Sampling rate of the samples in Data.IR and Data.Delay.",
    },
    "Data.SamplingRate:Units": {
        "default": "hertz",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "Unit of the sampling rate.",
    },
    "Data.Delay": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "IR, MR",
        "type": "double",
        "comment": "Additional delay of each IR (in samples, with the time interval as described by SamplingRate).",
    },
    "SourceUp": {
        "default": [0, 0, 1],
        "flags": None,
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "SourceView": {
        "default": [1, 0, 0],
        "flags": None,
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "SourceView:Type": {
        "default": "cartesian",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourceView:Units": {
        "default": "metre",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
}

SIMPLEFREEFIELDHRIR_1_2 = {
    "GLOBAL:Conventions": {
        "default": "SOFA",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Version": {
        "default": "2.1",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:SOFAConventions": {
        "default": "SimpleFreeFieldHRIR",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "This convention set is for impulse responses recorded under free-field conditions or conditions with irrelevant room information.",
    },
    "GLOBAL:SOFAConventionsVersion": {
        "default": "1.2",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIName": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:APIVersion": {
        "default": "",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationName": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:ApplicationVersion": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:AuthorContact": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Comment": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DataType": {
        "default": "FIR",
        "flags": "rm",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:History": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:License": {
        "default": "No license provided, ask the author for permission",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DatabaseName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "Unique name of the database to which these data belong.",
    },
    "GLOBAL:ListenerShortName": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "ID of the subject from the database.",
    },
    "GLOBAL:Organization": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:References": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:RoomType": {
        "default": "free field",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Origin": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateCreated": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:DateModified": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "GLOBAL:Title": {
        "default": "",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition": {
        "default": [[0, 0.09, 0], [0, -0.09, 0]],
        "flags": "m",
        "dimensions": "RCI",
        "type": "double",
        "comment": "",
    },
    "ReceiverPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ReceiverPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "The source position is assumed to vary around the listener.",
    },
    "SourcePosition:Type": {
        "default": "spherical",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourcePosition:Units": {
        "default": "degree, degree, metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition": {
        "default": [0, 0, 0],
        "flags": "m",
        "dimensions": "eCI, eCM",
        "type": "double",
        "comment": "Source consists of a single Emitter only.",
    },
    "EmitterPosition:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "EmitterPosition:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerUp": {
        "default": [0, 0, 1],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView": {
        "default": [1, 0, 0],
        "flags": "m",
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "ListenerView:Type": {
        "default": "cartesian",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "ListenerView:Units": {
        "default": "metre",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Data.IR": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "mrn",
        "type": "double",
        "comment": "",
    },
    "Data.SamplingRate": {
        "default": 48000,
        "flags": "m",
        "dimensions": "I, M",
        "type": "double",
        "comment": "Sampling rate of the samples in Data.IR and Data.Delay.",
    },
    "Data.SamplingRate:Units": {
        "default": "hertz",
        "flags": "m",
        "dimensions": None,
        "type": "attribute",
        "comment": "Unit of the sampling rate.",
    },
    "Data.Delay": {
        "default": [0, 0],
        "flags": "m",
        "dimensions": "IR, MR",
        "type": "double",
        "comment": "Additional delay of each IR (in samples, with the time interval as described by SamplingRate).",
    },
    "SourceUp": {
        "default": [0, 0, 1],
        "flags": None,
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "SourceView": {
        "default": [1, 0, 0],
        "flags": None,
        "dimensions": "IC, MC",
        "type": "double",
        "comment": "",
    },
    "SourceView:Type": {
        "default": "cartesian",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "SourceView:Units": {
        "default": "metre",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "",
    },
    "Normalization": {
        "default": 0,
        "flags": "I",
        "dimensions": None,
        "type": "double",
        "comment": "Describing normalization status.",
    },
    "Normalization:Description": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "Narrative explanation of the normalization.",
    },
    "Normalization:References": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "References to publications describing the normalization.",
    },
    "Normalization:URI": {
        "default": "",
        "flags": None,
        "dimensions": None,
        "type": "attribute",
        "comment": "URIs or DOIs to publications describing the normalization.",
    },
}

CONVENTIONS: dict[str, dict[str, dict[str, Any]]] = {
    "SimpleFreeFieldHRTF": {
        "1.0": SIMPLEFREEFIELDHRTF_1_0,
        "1.1": SIMPLEFREEFIELDHRTF_1_1,
        "1.2": SIMPLEFREEFIELDHRTF_1_2,
    },
    "SimpleFreeFieldHRIR": {
        "1.0": SIMPLEFREEFIELDHRIR_1_0,
        "1.1": SIMPLEFREEFIELDHRIR_1_1,
        "1.2": SIMPLEFREEFIELDHRIR_1_2,
    },
}
