[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hrtfpykit"
version = "0.0.1"
description = "Toolkit for loading, handling, analyzing, and visualizing HRTF data in Python"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Ariel Alvarez-Martinez" }]
keywords = ["audio", "hrtf", "sofa", "spatial-audio"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "numpy>=2.3.5",
  "scipy>=1.16.3",
  "matplotlib>=3.10.7",
  "netCDF4>=1.7.3",
]

[project.optional-dependencies]
test = [
  "pytest>=9.0.2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["hrtfpykit*"]
