from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Margins:
    """Default Matplotlib subplot margin and spacing configuration.

    :class:`~hrtfpykit.plots.default.Margins` stores the normalized figure
    bounds and inter-subplot spacing used by hrtfpykit layouts.
    :class:`~hrtfpykit.plots.figure.Figure` passes these values to
    matplotlib.figure.Figure.subplots_adjust after creating the subplot grid, so
    every high-level HRTF, HRIR, comparison, spectrum, and source-grid plot
    starts from a consistent page geometry.

    Notes
    -----
    left, right, bottom, and top use Matplotlib's normalized
    figure-coordinate convention, where 0.0 and 1.0 refer to the full
    figure extent. wspace and hspace follow Matplotlib's subplot spacing
    convention and are interpreted relative to average subplot width and height.
    Custom plots can pass :class:`~hrtfpykit.plots.default.Margins` instances
    into layout constructors when a figure needs more room for labels, colorbars,
    legends, or figure titles.

    Attributes
    ----------
    top, bottom, left, right : float
        Normalized figure bounds used to position the subplot area.
    wspace, hspace : float
        Horizontal and vertical spacing between subplots.

    """

    top: float = 0.9
    bottom: float = 0.1
    left: float = 0.1
    right: float = 0.9
    wspace: float = 0.35
    hspace: float = 0.35


@dataclass(frozen=True)
class FigureSize:
    """Default figure dimensions used by plot layouts.

    :class:`~hrtfpykit.plots.default.FigureSize` stores the width and height,
    in Matplotlib inches, used by layouts that do not provide a custom figsize
    tuple. The plotting wrapper converts
    :class:`~hrtfpykit.plots.default.FigureSize` values to a Matplotlib
    ``figsize`` tuple before calling matplotlib.pyplot.subplots.

    Notes
    -----
    Larger or specialized layouts can either create a different
    :class:`~hrtfpykit.plots.default.FigureSize` instance or pass a plain
    (width, height) tuple directly to the layout. The default size is intended
    for single-panel and simple stacked plots.

    Attributes
    ----------
    width : float
        Figure width in inches.
    height : float
        Figure height in inches.

    """

    width: float = 8
    height: float = 6


@dataclass(frozen=True)
class RC:
    """Default Matplotlib text sizes used by hrtfpykit figures.

    :class:`~hrtfpykit.plots.default.RC` stores the font-size values applied by
    :meth:`~hrtfpykit.plots.figure.Figure.configure_rc`. These values control the
    text scale for axes, tick labels, legends, subplot titles, and figure-level
    titles so plots generated by different modules share a consistent visual
    hierarchy.

    Notes
    -----
    Values are passed directly to Matplotlib rcParams and are interpreted in
    points by Matplotlib. default maps to font.size, while the other
    fields map to the specific axes, tick, legend, and figure-title rcParams
    used by the plotting wrapper.

    Attributes
    ----------
    legend_title : float
        Font size for legend titles.
    legend : float
        Font size for legend labels.
    ticks : float
        Font size for x- and y-axis tick labels.
    axis_labels : float
        Font size for axis labels.
    default : float
        Global default font size.
    axis_title : float
        Font size for subplot titles.
    fig_title : float
        Font size for figure-level titles.

    """

    legend_title: float = 10
    legend: float = 9
    ticks: float = 7
    axis_labels: float = 9
    default: float = 10
    axis_title: float = 10
    fig_title: float = 12
